# test profile, 测试环境配置
spring:
    datasource:
        url: jdbc:mysql://10.50.208.248:18805/cicd_default?useUnicode=true&characterEncoding=utf8
        username: edas
        password: lpwpFl5SJq7TRDvrwm2
        driver-class-name: com.mysql.jdbc.Driver