debug: true

server:
    port: 28504

spring:
    datasource:
        url: jdbc:mysql://10.50.208.248:18805/cicd_dev?useUnicode=true&characterEncoding=utf8
        username: edas
        password: lpwpFl5SJq7TRDvrwm2
        driver-class-name: com.mysql.cj.jdbc.Driver

    cloud:
        nacos:
            config:
                enabled: false
            discovery:
                username: nacos
                password: MrP^(Dw4(&kOf
                enabled: true
                group: paas_default
                server-addr: 10.50.208.131:8848
                namespace: dev
                service: cicd-gateway-dev
    redis:
        host: 127.0.0.1
        port: 6379
        timeout: PT10S
        password:
        database: 1
    
    sleuth:
        enabled: false

swagger:
    group: Controller
    basePackage: com.ctg.cicd.gate.controller
    title: ctgcloud-edas-pipeline RESTful APIs
    description: ctgcloud-cicd-gate RESTful API
    version: 1.0.0-SNAPSHOT
    openApi:
        group: OpenApi
        basePackage: com.ctg.cicd.gate.controller
        title: ctgcloud-edas-pipeline Open APIs
        description: ctgcloud-edas-pipeline Open API
        version: 1.0.0-SNAPSHOT

paas:
    gateway:
        #        dcos-url: http://localhost:9111/eadp
        dcos-url: http://10.50.208.131:8971/api/openApi/paas/ccse
        mse-url: http://10.50.208.101:28311/gateway/openapi/MSERCM
        app-key: e3aac1e6ef6966b05837ab0d234ec776
        app-secret: ENC(yyrVGHdGykmJDaUnp9fWAQbSHWCoR2GduCYZwFrTRni9+ZQPAI51FZ/laLdvMpfQgACebbZUABE=)

logging:
    config: classpath:config/logback-spring.xml

mybatis-plus:
    mapper-locations: classpath*:mapper/**/*.xml
    config-location: classpath:config/mybatis-config.xml

# mybatis分页
pagehelper:
    helperDialect: mysql
    reasonable: true
    rowBoundsWithCount: true
    offsetAsPageNum: true

#spring-security相关
default:
    bake:
        account: default
    securityGroups: [ ]
    vpc:
        securityGroups: [ ]

oss:
    endpoint: 10.50.208.120:7480
    accessKey: PT9FS1A6AVDAB7TU3WES
    secretKey: HmBanq0QreGP3QAf6O1u6hkN9xvbAum9SSvR74VB

docker-hub:
    url: 10.50.208.131:8201
    origin-image-org: library
    base-image-org: library
    business-org: business
    
jasypt:
    encryptor:
        salt: m8gF9@ith7GX246OV5P!yA


